version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./React
      dockerfile: Dockerfile
    volumes:
      - ".:/frontend"
      - "/frontend/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
