# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /frontend

COPY . /frontend
# add `/app/node_modules/.bin` to $PATH

# install and cache app dependencies
COPY package.json /frontend/package.json
RUN npm install --silent

# start app
CMD ["npm", "run", "start"]